services:

  backend:
    restart: always
    build: ./backend/
    container_name: backend
    env_file: ./.env
    volumes:
      - sqlite:/var/lib/sqlite
      - avatars:/var/www/server/public/avatars
      - vault_key:/vault/config
      # - ./backend/src/public:/var/www/server/public # remove comment for working on webpage
    networks:
      - backend_net
      - vault_net
    develop:
      watch:
        - path: ./backend/src
          action: rebuild
          target: /var/www/server
    depends_on:
      - vault

  frontend:
    restart: always
    build: ./frontend/
    container_name: frontend
    env_file: ./.env
    depends_on:
      - backend
    networks:
      - frontend_net
      - backend_net
    develop:
      watch:
        - path: ./frontend/src
          action: rebuild
          target: /var/www/html

  modsecurity:
    restart: always
    build: ./modsecurity/
    container_name: modsecurity
    volumes:
      - cert:/etc/nginx/conf/ssl
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      - frontend_net
      - backend_net
      - entrypoint_net
    depends_on:
      - frontend
      - backend
    develop:
      watch:
        - path: ./frontend/srcs
          action: rebuild
          target: /var/www/html
        - path: ./frontend/conf/nginx.conf
          action: rebuild
          target: /etc/nginx/nginx.conf

  vault:
    restart: always
    image: hashicorp/vault:1.21
    container_name: vault
    cap_add:
      - IPC_LOCK
    volumes:
      - vault:/vault/file
      - ./vault/conf:/vault/conf:ro
    networks:
      - vault_net
    environment:
      VAULT_API_ADDR: "http://127.0.0.1:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
    command: vault server -config=/vault/conf/vault.hcl

networks:
  entrypoint_net:
    driver: bridge
  backend_net:
  frontend_net:
  vault_net:

volumes:
  sqlite:
    name: sqlite
  cert:
    name: cert
  avatars:
    name: avatars
  vault:
    name: vault
  vault_key:
