services:

  backend:
    # restart: always
    build: ./backend/
    container_name: backend
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - sqlite:/var/lib/sqlite
    networks:
      - db

  frontend:
    restart: always
    build: ./frontend/
    container_name: frontend
    env_file: ./.env
    depends_on:
      - backend
    volumes:
      - front_data:/var/www/html
    networks:
      - web
      - db

  modsecurity:
    restart: always
    build: ./modsecurity/
    container_name: modsecurity
    depends_on:
      - frontend
    volumes:
      - cert:/etc/nginx/conf/ssl
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      - transcendence
      - web

networks:
  transcendence:
    driver: bridge
  db:
  web:

volumes:
  sqlite:
    name: sqlite
  front_data:
    name: front_data
  cert:
    name: cert
