services:

  backend:
    # restart: always
    build: ./backend/
    container_name: backend
    env_file: ./.env
    ports:
      - "3309:3309"
      - "9000:9000"
    volumes:
      - sqlite:/var/lib/sqlite
    networks:
      - transcendence

  frontend:
    restart: always
    build: ./frontend/
    container_name: frontend
    env_file: ./.env
    ports:
      - "8080:8080"
    volumes:
      - front_data:/var/www/html
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  sqlite:
    name: sqlite
  front_data:
    name: front_data
